# Generated by Django 4.2.30 on 2026-04-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='status_override',
            field=models.CharField(blank=True, choices=[('at_risk', 'At Risk'), ('healthy', 'Healthy')], help_text='Agent-set override: forces at_risk or healthy regardless of timeline.', max_length=20, null=True),
        ),
    ]
